### ISSUE TITLE
Bug: Can not set GHA_Meta

### ISSUE THREAD

**Issue by pepesenaris** [CircleCI-Public/trigger-circleci-pipeline-action#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Fails when using setting the GHA_Meta input

```
 /home/runner/work/_actions/CircleCI-Public/trigger-circleci-pipeline-action/v1.0.2/dist/index.js:12739
    Object.assign("GHA_Meta", metaData);
           ^
  
  TypeError: Cannot assign to read only property '0' of object '[object String]'
      at Function.assign (<anonymous>)
      at /home/runner/work/_actions/CircleCI-Public/trigger-circleci-pipeline-action/v1.0.2/dist/index.js:12739:10
      at /home/runner/work/_actions/CircleCI-Public/trigger-circleci-pipeline-action/v1.0.2/dist/index.js:12772:3
      at Object.<anonymous> (/home/runner/work/_actions/CircleCI-Public/trigger-circleci-pipeline-action/v1.0.2/dist/index.js:12775:12)
      at Module._compile (internal/modules/cjs/loader.js:959:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
      at Module.load (internal/modules/cjs/loader.js:815:32)
      at Function.Module._load (internal/modules/cjs/loader.js:727:14)
      at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
      at internal/main/run_main_module.js:17:11
```

### Minimum reproduction code

https://gist.github.com/pepesenaris/e069b56e42aefcc4c5a4f356782db519

### Steps to reproduce

Just setting a value in GHA_Meta

### Expected behavior

Allows to pass the GHA_Meta input key

### GitHub Action Version

1.0.2

**Comment by pepesenaris** [comment]
https://github.com/CircleCI-Public/trigger-circleci-pipeline-action/pull/3 Proposed fix
